# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: demo
spec:
  project: default

  source:
    repoURL: https://github.com/Leonardoleee/argocd-example-apps.git
    targetRevision: HEAD
    path: kustomize-guestbook
  destination:
    server: https://C379E58CEA9BF077EE06C36B1454C222.gr7.me-central-1.eks.amazonaws.com
    namespace: demo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true